SpectorMax/Controllers/NotificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SpectorMax.Entities.Classes;
using SpectorMax.Models;
using SpectorMaxDAL;
using System.IO;
using System.Web;
using System.Collections;
using System.Drawing;
using System.Drawing.Imaging;
using System.Drawing.Drawing2D;
namespace SpectorMax.Controllers
{
    public class NotificationController : BaseController
    {

        #region Global Variables
        private SpectorMaxContext context = new SpectorMaxContext();
        private MessageToShow _messageToShow = new MessageToShow();
        public static List<TableNamesOrderId> objTableNamesOrderId = new List<TableNamesOrderId>();
        List<string> imagesNameList = new List<string>();
        string I_OrderId = string.Empty;
        #endregion

        #region Index
        //
        // GET: /Notification/

        public ActionResult Index()
        {

            List<PropertyAddress> objList_PropertyAddress = new List<PropertyAddress>();
            List<inspectionorder> ArrayOfOrderPlaced = context.InspectionOrders.Where(x => x.RequesterID == Sessions.LoggedInUser.UserId && x.IsUpdatable == true).ToList();
            List<string> Order_id = new List<string>();

            foreach (var item in ArrayOfOrderPlaced)
            {
                if (context.ElectrialCommanSection.Any(x => x.ReportID == item.InspectionOrderID && x.ConditionID == "3"))
                {
                    objTableNamesOrderId.Add(new TableNamesOrderId { TableName = "ElectrialCommanSection", OrderID = item.InspectionOrderID });
                }
                if (context.ElectricalPanel.Any(x => x.ReportID == item.InspectionOrderID && x.ConditionID == "3"))
                {
                    objTableNamesOrderId.Add(new TableNamesOrderId { TableName = "ElectricalPanel", OrderID = item.InspectionOrderID });
                }
                if (context.ElectricalRoom.Any(x => x.ReportID == item.InspectionOrderID && x.ConditionID == "3"))
                {
                    objTableNamesOrderId.Add(new TableNamesOrderId { TableName = "ElectricalRoom", OrderID = item.InspectionOrderID });
                }
                if (context.ElectricalService.Any(x => x.ReportID == item.InspectionOrderID && x.ConditionID == "3"))
                {
                    objTableNamesOrderId.Add(new TableNamesOrderId { TableName = "ElectricalService", OrderID = item.InspectionOrderID });

                }
                if (context.Appliancescommonsections.Any(x => x.InspectionOrderID == item.InspectionOrderID && x.CheckboxID == "3"))
                {
                    objTableNamesOrderId.Add(new TableNamesOrderId { TableName = "Appliancescommonsections", OrderID = item.InspectionOrderID });

                }

                if (context.AppliancesDishwashDisposalRange_sections.Any(x => x.InsepectionOrderID == item.InspectionOrderID && x.CheckBoxID == "3"))
                {
                    objTableNamesOrderId.Add(new TableNamesOrderId { TableName = "AppliancesDishwashDisposalRange_sections", OrderID = item.InspectionOrderID });

                }
                if (context.AppliancesDryerDoorBellSectiions.Any(x => x.InspectionOrderID == item.InspectionOrderID && x.CheckBoxID == "3"))
                {
                    objTableNamesOrderId.Add(new TableNamesOrderId { TableName = "AppliancesDryerDoorBellSectiions", OrderID = item.InspectionOrderID });

                }
                if (context.AppliancesHoodVentOtherSections.Any(x => x.InspectionOrderId == item.InspectionOrderID && x.CheckBoxID == "3"))
                {
                    objTableNamesOrderId.Add(new TableNamesOrderId { TableName = "AppliancesHoodVentOtherSections", OrderID = item.InspectionOrderID });

                }
                if (context.AppliancesOvenSections.Any(x => x.InspectionOrderID == item.InspectionOrderID && x.CheckboxID == "3"))
                {
                    objTableNamesOrderId.Add(new TableNamesOrderId { TableName = "AppliancesOvenSections", OrderID = item.InspectionOrderID });

                }
                if (context.GroundCommonSections.Any(x => x.InspectionOrderID == item.InspectionOrderID && x.CheckBoxID == "3"))
                {
                    objTableNamesOrderId.Add(new TableNamesOrderId { TableName = "GroundCommonSections", OrderID = item.InspectionOrderID });

                }
                if (context.GroundGassections.Any(x => x.InspectionOrderID == item.InspectionOrderID && x.CheckBoxID == "3"))
                {
                    objTableNamesOrderId.Add(new TableNamesOrderId { TableName = "GroundGassections", OrderID = item.InspectionOrderID });

                }
                if (context.GroundH2OSections.Any(x => x.InspectionOrderID == item.InspectionOrderID && x.CheckBoxID == "3"))
                {
                    objTableNamesOrderId.Add(new TableNamesOrderId { TableName = "GroundH2OSections", OrderID = item.InspectionOrderID });

                }
                if (context.GroundSewerSections.Any(x => x.C_InspectionOrderID == item.InspectionOrderID && x.CheckBoxID == "3"))
                {
                    objTableNamesOrderId.Add(new TableNamesOrderId { TableName = "GroundSewerSections", OrderID = item.InspectionOrderID });
                }
                if (context.GroundSprinkSysSections.Any(x => x.InspectionOrderID == item.InspectionOrderID && x.CheckBoxID == "3"))
                {
                    objTableNamesOrderId.Add(new TableNamesOrderId { TableName = "GroundSprinkSysSections", OrderID = item.InspectionOrderID });
                }
                if (context.HVACCommonSections.Any(x => x.InspectionOrderID == item.InspectionOrderID && x.CheckBoxID == "3"))
                {
                    objTableNamesOrderId.Add(new TableNamesOrderId { TableName = "HVACCommonSections", OrderID = item.InspectionOrderID });
                }
                if (context.HVACCoolings.Any(x => x.InspectionOrderID == item.InspectionOrderID && x.CheckBoxID == "3"))
                {
                    objTableNamesOrderId.Add(new TableNamesOrderId { TableName = "HVACCoolings", OrderID = item.InspectionOrderID });
                }
                if (context.HVACDuctsVents.Any(x => x.InspectionOrderID == item.InspectionOrderID && x.CheckBoxID == "3"))
                {
                    objTableNamesOrderId.Add(new TableNamesOrderId { TableName = "HVACDuctsVents", OrderID = item.InspectionOrderID });
                }
                if (context.HVACEquipBoileRadiantSections.Any(x => x.InspectionOrderId == item.InspectionOrderID && x.CheckBoxID == "3"))
                {
                    objTableNamesOrderId.Add(new TableNamesOrderId { TableName = "HVACEquipBoileRadiantSections", OrderID = item.InspectionOrderID });
                }
                if (context.OptionalCommonSections.Any(x => x.InspectionOrderID == item.InspectionOrderID && x.CheckBoxID == "3"))
                {
                    objTableNamesOrderId.Add(new TableNamesOrderId { TableName = "OptionalCommonSections", OrderID = item.InspectionOrderID });
                }
                if (context.PlumbingMainlineKitchenOthers_Sections.Any(x => x.InspectionOrderId == item.InspectionOrderID && x.CheckBoxID == "3"))
                {
                    objTableNamesOrderId.Add(new TableNamesOrderId { TableName = "PlumbingMainlineKitchenOthers_Sections", OrderID = item.InspectionOrderID });
                }
                if (context.PlumbingWaterheats.Any(x => x.InspectionOrderId == item.InspectionOrderID && x.CheckBoxID == "3"))
                {
                    objTableNamesOrderId.Add(new TableNamesOrderId { TableName = "PlumbingWaterheats", OrderID = item.InspectionOrderID });
                }
                if (context.StructuralCommonSections.Any(x => x.InspectionOrderID == item.InspectionOrderID && x.CheckBoxiD == "3"))
                {
                    objTableNamesOrderId.Add(new TableNamesOrderId { TableName = "StructuralCommonSections", OrderID = item.InspectionOrderID });
                }
            }

            var distinctOrderId = objTableNamesOrderId.Select(x => x.OrderID).Distinct().ToList();

            foreach (var item in distinctOrderId)
            {
                PropertyAddress objPropertyAddress = new PropertyAddress();

                var Property_Address = context.InsectionOrderDetails.Where(x => x.InspectionOrderId == item).FirstOrDefault();
                objPropertyAddress.OwnerFirstName = Property_Address.OwnerFirstName;
                objPropertyAddress.OwnerLastName = Property_Address.OwnerLastName;
                objPropertyAddress.StreetAddress = Property_Address.StreetAddess;
                objPropertyAddress.City = Property_Address.City;
                objPropertyAddress.State = Property_Address.State;
                objPropertyAddress.Zip = Property_Address.Zip;
                objPropertyAddress.OrderID = item;
                objList_PropertyAddress.Add(objPropertyAddress);
            }

            return View(objList_PropertyAddress);
        }
        #endregion

        #region GetDetails
        /// <summary>
        /// POST:// Method for Get List of all subsection(nofification) those are need to maintenance against inspectionorderid and sectionid
        /// </summary>
        /// <param name="OrderID"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetDetails(string OrderID)
        {

            //ViewBag.OrderID = OrderID;
            List<PropertyAddress> objDetails = new List<PropertyAddress>();
            string result = RenderRazorViewToString("~/Views/Notification/_PartialMaintenanceDetails.cshtml", objDetails);
            return ReturnJson(result);
        }
        #endregion


        #region PartialUpdateSubSectionInfor
        /// <summary>

SpectorMax/Views/Notification/Index.cshtml
@{
    ViewBag.Title = "MaintenanceRequired";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using SpectorMax.Entities.Classes
<script src="@Url.Content("~/Scripts/jquery.blockUI.js")"></script>
<link href="@Url.Content("~/Content/TablesCss/demo_page.css")" rel="stylesheet">
<link href="@Url.Content("~/Content/TablesCss/header.ccss.css")" rel="stylesheet">
<link href="@Url.Content("~/Content/TablesCss/demo_table.css")" rel="stylesheet">
<script src="@Url.Content("~/Scripts/jquery.dataTables.js")" type="text/javascript"></script>

<section class="top_headerbar"></section>
<section id="wrapper">
    <div id="P1">
        @Html.Partial("_PartialMaintenanceRequired")
    </div>
    <div id="P2">
        @Html.Partial("_PartialMaintenanceDetails")
    </div>
    <div id="P3">
        @Html.Partial("_PartialUpdateSection")
    </div>
</section>
<script type="text/javascript">
    $(document).ready(function () {
        var sessionData =  @Html.Raw(Json.Encode(Sessions.LoggedInUser));

        if(sessionData != null)
        { 
            if(sessionData.RoleName == "Home Buyer")
            {
                $("#anchorLogoImage").attr("href", $URL._BuyerDashBoard);
            }
        }
        $('#tblMaintenanceReq').dataTable();
        $("#P2").hide();
        $("#P3").hide();

        $("#tblMaintenanceReq tr").click(function () {
            /*initializing Progress Bar*/
            $.blockUI({
                css: {
                    border: 'none',
                    padding: '15px',
                    backgroundColor: '#000',
                    '-webkit-border-radius': '10px',
                    '-moz-border-radius': '10px',
                    opacity: .5,
                    color: '#fff'
                }
            });
            $("#P1").hide();
            $("#P3").hide();
            $("#P2").show();
            $.ajax({
                type: "POST",
                url: "Notification/GetDetails",
                dataType: "Json",
                data: {orderId : this.cells[1].children.anchorMaintenanceReq1.dataset.orderid},
                success: function (result) {
                    $("#P2").html("");
                    setTimeout($.unblockUI, 1000);
                    $("#P2").html(result);
                },
            });
        });
    });
</script>

SpectorMax/Views/Notification/NewNotification.cshtml
@model List<SpectorMax.Entities.Classes.PropertyAddress>
@{
    ViewBag.Title = "NewNotification";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script src="@Url.Content("~/Scripts/jquery.blockUI.js")"></script>
<link href="@Url.Content("~/Content/TablesCss/demo_page.css")" rel="stylesheet">
<link href="@Url.Content("~/Content/TablesCss/header.ccss.css")" rel="stylesheet">
<link href="@Url.Content("~/Content/TablesCss/demo_table.css")" rel="stylesheet">

<script src="@Url.Content("~/Scripts/jquery.dataTables.js")" type="text/javascript"></script>
<script>
    $(function () {
        $("#tabs").tabs();
        $(document).ready(function () {
        if (document.URL.indexOf("UpdateStatus") > 0) {
          
            $("#SecondTab").addClass('ui-state-default ui-corner-top .ui-state-active, .ui-widget-content .ui-widget-header .ui-state-active ui-tabs-active ui-state-active');
            $("#FirstTab").removeClass('ui-state-default ui-corner-top .ui-state-active, .ui-widget-content .ui-widget-header .ui-state-active ui-tabs-active ui-state-active');
            $("#FirstTab").addClass('ui-state-default ui-corner-top');
            $("[href$='False']").each(function () {
                var href = $(this).attr("href");
                var res = href.replace(/False/g, "True");
                $(this).attr("href", res);
            });
        }
    });
    });
    function onClickNewOrders() {
        $(location).attr("href", $URL._NotificationDashboard);
    }
    $(document).ready(function () {
        $("#RejectOrders").click(function () {
            var url = $URL._GetRejectedOrders + "/" + 1;
            var targetDiv = "#tabs-" + 2;
            var type = "UpdateOrders"
            showLoader();
            $.get(url, null, function (result) {
                $(targetDiv).html(result);
                hideLoader();
            });
        });
    });
</script>
<section id="container">
    <section class="payment">
        <section>
            <div id="tabs" style="min-height: 600px;">
                <ul>
                    <li id="FirstTab"><a id="NewOrders" onclick="onClickNewOrders();" href="#tabs-1">New Inspection Orders(@ViewBag.NewNotification)</a></li>
                    <li id="SecondTab"><a href="#tabs-2" id="RejectOrders">Updated Inspection Orders(@ViewBag.UpdatedNotification)</a></li>
                </ul>
                <div id="tabs-1" style="margin-top: 35px">
                    <table style="width: 100%; float: right" cellpadding="0" cellspacing="0" border="0" class="table" id="tblMaintenanceReq">
                        <thead>
                            <tr>
                                <th width="70%" class="tbl_head bod_rgt">Property Address</th>
                                <th width="30%" class="tbl_head bod_rgt">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                if (item.IsInspectorComment)
                                {   
                                <tr bgcolor="#C6DEFF">
                                    <td class="bod_rgt">@item.OwnerFirstName @item.OwnerLastName, @item.StreetAddress,@item.City,@item.State,@item.Zip </td>
                                    <td class="bod_rgt"><a href="@Url.Action("MaintananceDetails", "Notification", new { OrderID = @item.OrderID, IsUpdated = false })" data-orderid="@item.OrderID" id="anchorMaintenanceReq1">View Detail</a></td>
                                </tr>
                                }
                                else
                                {
                                <tr>
                                    <td class="bod_rgt">@item.OwnerFirstName @item.OwnerLastName, @item.StreetAddress,@item.City,@item.State,@item.Zip </td>
                                    <td class="bod_rgt"><a href="@Url.Action("MaintananceDetails", "Notification", new { OrderID = @item.OrderID, IsUpdated = false })" data-orderid="@item.OrderID" id="anchorMaintenanceReq1">View Detail</a></td>
                                </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
                <div style="margin-top: 35px" id="tabs-2">
                </div>
                <div style="margin-top: 35px" id="tabs-3">
                </div>
            </div>
        </section>
    </section>
    <section class="clr"></section>
</section>
<!-- Loader-->
<div id="loadingModel" class="displayNone overlayPage">
    <div class=" loaderPage">
        <div>
            <img src='@Url.Content("~/Content/Images/loading_big.gif")' />
        </div>
        <div>
            Loading..
        </div>
    </div>
</div>
<!-- /Loader -->
<script type="text/javascript">
    $("#tblMaintenanceReq").dataTable();

    $(document).ready(function () {

        //$("#tblMaintenanceReq tr").click(function () {
        //    /*initializing Progress Bar*/
        //    $.blockUI({
        //        css: {
        //            border: 'none',
        //            padding: '15px',
        //            backgroundColor: '#000',
        //            '-webkit-border-radius': '10px',
        //            '-moz-border-radius': '10px',
        //            opacity: .5,
        //            color: '#fff'
        //        }
        //    });
        //    $("#P1").hide();
        //    $("#P3").hide();
        //    $("#P2").show();
        //    $.ajax({
        //        type: "POST",
        //        url: $URL._GetNotificationDetails,
        //        dataType: "Json",
        //        data: { orderId: this.cells[1].children.anchorMaintenanceReq1.dataset.orderid },
        //        success: function (result) {
        //            $("#P2").html("");
        //            setTimeout($.unblockUI, 1000);
        //            $("#P2").html(result);
        //        },
        //    });
        //});

    });
    function showLoader() {
        $("#loadingModel").show();
    }
    function hideLoader() {
        $("#loadingModel").hide();
    }

</script>

SpectorMax/Views/Notification/UpdateSubSectionInfo.cshtml
@{
    ViewBag.Title = "UpdateSubSectionInfo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section>
    <section id="container">
        <section class="payment">
            <section class="registration">

                @Html.Partial("_PartialUpdateSubSectionInfor")

            </section>
        </section>
        <section class="clr"></section>
    </section>
    <section class="clr"></section>
</section>

SpectorMax/Views/Notification/UserNotifications.cshtml
@model SpectorMax.Entities.Classes.UserNotificationsEntity

@{
    ViewBag.Title = "MaintenanceRequired";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="tbl_content">
    <table width="60%" style="margin: 10px" cellspacing="0">
        <tr>
            <td>
                @Html.TextBoxFor(model => model.firstname, new { @id = "txtfirstname", @class = "simple_input" })
            </td>
            <td>
                @Html.TextBoxFor(model => model.lastname, new { @id = "txtlastname", @class = "simple_input" })
            </td>
            <td>
                @Html.TextBoxFor(model => model.zipcode, new { @id = "txtzipcode", @class = "simple_input" })
            </td>
            <td>
                <input type="button" class="btn" id="btnSearchReport" value="Search" />
            </td>
           
        </tr>
    </table>
    <table width="40%" style="margin: 10px; display: block" id="inspectorDetails" cellspacing="0">
        <tr>
            <td>
                <label>To</label></td>
            <td>
                @Html.TextBoxFor(model => model.firstname, new { @id = "txtToFirstName", @class = "simple_input" })
            </td>
            <td>
                @Html.TextBoxFor(model => model.firstname, new { @id = "txtTolastName", @class = "simple_input" })
            </td>
            <td>
                <input type="button" class="btn" id="btncmpmsg" value="Compose Message" />
            </td>
            <td></td>
        </tr>
    </table>
    <table width="40%" style="margin: 10px; display: none" id="tblmsgcompose" cellspacing="0">
        <tr>
            <td>
                <label>To</label></td>
            <td>
                @Html.TextBoxFor(model => model.firstname, new { @id = "txtToFirstName", @class = "simple_input" })
            </td>
            <td>
                @Html.TextAreaFor(model => model.Message, new { @id = "txtmsg", @class = "simple_input" })
            </td>
            <td>
                <input type="button" class="btn" id="btnsendmsg" value="Search" />
            </td>
            <td></td>
        </tr>
    </table>
    @if (Model.msg_lst != null)
    {
    <table style="width: 100%; float: left" cellpadding="0" cellspacing="0" border="0" class="table" id="tblnotifications">
                <thead>
                    <tr>
                        <th width="1%" class="tbl_head bod_rgt"><input type="checkbox" /></th>
                        <th width="20%" class="tbl_head bod_rgt">From</th>
                        <th width="10%" class="tbl_head bod_rgt">Subject</th>
                        <th width="15%" class="tbl_head bod_rgt">Date</th>
                        <th width="20%" class="tbl_head bod_rgt"></th>
                    </tr>
                </thead>
                <tbody>
                        @foreach (var item in Model.msg_lst)
                        {
                        <tr>
                            <td class="bod_rgt">@item.From"</td>
                            <td class="bod_rgt">@item.Subject"</td> 
                            <td class="bod_rgt">@item.CreatedDate"</td> 
                            <td class="bod_rgt"><a id="Detail" class="redd" data-msgid="@item.msd_id">View Message</a></td> 
                        </tr>
                        }
                <tbody>
    </table>
    }
    <section class="clr"></section>
</section>
<script type="text/javascript">

    $("#btnSearchReport").click(function () {
        $.ajax({
            url: $URL._GetInspector_Notifications,
            type: "POST",
            data: { firstname: $("#txtfirstname").val(), lastname: $("#txtfirstname").val(), zipcode: $("#txtzipcode").val() },
                success: function (result) {
                    $("#txtToFirstName").val(result.FirstName);
                    $("#txtTolastName").val(result.LastName);
                }
            });
    });

    $("#btncmpmsg").click(function () {
        $("#tblmsgcompose").show();
    });;

</script>

SpectorMax/Views/Notification/_PartialMaintenanceRequired.cshtml
@model List<SpectorMax.Entities.Classes.PropertyAddress>

<section id="container">
    <section class="payment">
        <h2 style="width:260px;">Maintenance Required</h2>
        <section class="tbl_content">
            <table style="width:100%; float:right"  cellpadding="0" cellspacing="0" border="0" class="table" id="tblMaintenanceReq">
                <thead>
                <tr>
                    <th width="70%" class="tbl_head bod_rgt">Property Address</th>
                    <th width="30%" class="tbl_head bod_rgt">Action</th>
                </tr>
                    </thead>
                <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="bod_rgt">@item.OwnerFirstName @item.OwnerLastName, @item.StreetAddress,@item.City,@item.State,@item.Zip </td>
                        <td class="bod_rgt"><a href="javascript://void(0);" data-orderid="@item.OrderID" id="anchorMaintenanceReq1">View Detail</a></td>
                    </tr>
                }
                    </tbody>
            </table>
        </section>
        <section class="clr"></section>
    </section>
    <section class="clr"></section>
</section>
<script type="text/javascript">
   
</script>

SpectorMax/Views/Notification/_PartialUpdateSection.cshtml
       <section id="container">
            <section class="payment">

                <div></div>
                <table style="height:400px;width: 100%;">
                    <tr>
                        <td style="padding-left: 100px;">
                            <label>Comments:</label>
                        </td>
                        <td></td>
                        <td style="padding-left: 100px;">
                            <input type="text" class="simple_input big_text_box" /></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><input type="text" class="simple_input big_text_box" /></td>
                        <td>
                            <input type="button" class="btn" value="Browse" /></td>
                    </tr>

                    <tr>
                        <td style="padding-left: 100px;">
                            <input type="button" id="btnViewPreviousInvoices" class="dbtn" value="View Previous Invoices" />
                        </td>
                        <td></td>
                        <td style="padding-left: 100px;">
                            <input type="button" id="btnNotification" class="dbtn" value="Notification" /></td>
                    </tr>

                </table>
                <section class="clr"></section>
            </section>
            <section class="clr"></section>
        </section>

SpectorMax/Views/Notification/_RejectedNotifications.cshtml
@model List<SpectorMax.Entities.Classes.PropertyAddress>

@using SpectorMax.Entities.Classes
<script src="@Url.Content("~/Scripts/FineUploader.js")" type="text/javascript"></script>
<link href="@Url.Content("~/Content/FineUpload.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/jquery.blockUI.js")"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#tblRejectNotifications").dataTable();
    });
</script>


<section class="tbl_content">
    <table style="width: 100%; float: right" cellpadding="0" cellspacing="0" border="0" class="table" id="tblRejectNotifications">
        <thead>
            <tr>
                <th width="70%" class="tbl_head bod_rgt">Property Address</th>
                <th width="30%" class="tbl_head bod_rgt">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                if (item.IsInspectorComment)
                {
                <tr bgcolor="#C6DEFF">
                    <td class="bod_rgt">@item.OwnerFirstName @item.OwnerLastName, @item.StreetAddress,@item.City,@item.State,@item.Zip </td>
                    <td class="bod_rgt"><a data-sectionid="@item.SectionID" data-subsectionid="@item.SubSectionID" href="@Url.Action("MaintananceDetails", "Notification", new { OrderID = @item.OrderID, IsUpdated = true })" data-orderid="@item.OrderID" id="anchorMaintenanceReq1">View Detail</a></td>
                </tr>
                }
                else
                {
                <tr>
                    <td class="bod_rgt">@item.OwnerFirstName @item.OwnerLastName, @item.StreetAddress,@item.City,@item.State,@item.Zip </td>
                    <td class="bod_rgt"><a data-sectionid="@item.SectionID" data-subsectionid="@item.SubSectionID" href="@Url.Action("MaintananceDetails", "Notification", new { OrderID = @item.OrderID, IsUpdated = true })" data-orderid="@item.OrderID" id="anchorMaintenanceReq1">View Detail</a></td>
                </tr>
                }
            }
        </tbody>
    </table>
    <section class="clr"></section>
</section>

SpectorMax/Views/Notification/_UpdatedNotifications.cshtml
@model List<SpectorMax.Entities.Classes.PropertyAddress>

@using SpectorMax.Entities.Classes
<script src="@Url.Content("~/Scripts/FineUploader.js")" type="text/javascript"></script>
<link href="@Url.Content("~/Content/FineUpload.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/jquery.blockUI.js")"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#tblUpdateNotifications").dataTable();
    });
</script>

     
        <section class="tbl_content">
 <table style="width: 100%; float: right" cellpadding="0" cellspacing="0" border="0" class="table" id="tblUpdateNotifications">
                        <thead>
                            <tr>
                                <th width="70%" class="tbl_head bod_rgt">Property Address</th>
                                <th width="30%" class="tbl_head bod_rgt">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td class="bod_rgt">@item.OwnerFirstName @item.OwnerLastName, @item.StreetAddress,@item.City,@item.State,@item.Zip </td>
                                    <td class="bod_rgt"><a href="@Url.Action("MaintananceDetails", "Notification", new { OrderID=@item.OrderID})" data-orderid="@item.OrderID" id="anchorMaintenanceReq1">View Detail</a></td>
                                </tr>
                            }
                        </tbody>
  </table>
             </section>
        <section class="clr"></section>
    