SpectorMax/Controllers/InspectorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Web;
using System.Web.Mvc;
using SpectorMax.Models;
using SpectorMax.Entities.Classes;
using SpectorMaxDAL;
using System.IO;
using System.Drawing;
using System.Web.Script.Serialization;
using MySql.Data.MySqlClient;
using System.Configuration;
using Newtonsoft.Json;
namespace SpectorMax.Controllers
{
    public class InspectorController : BaseController
    {


        #region Global Variables
        /*Initilizing Context*/
        private SpectorMaxContext context = new SpectorMaxContext();
        MessageToShow _messageToShow = new MessageToShow();
        // static List<MainSectionList> mainSectionList = new List<MainSectionList>();
        // static List<SubSectionList> subSectionList = new List<SubSectionList>();
        List<string> imagesNameList = new List<string>();
        string connStr = ConfigurationManager.ConnectionStrings["SpectorMaxConnectionString"].ConnectionString;
        #endregion

        #region Index
        //
        // GET: /Inspector/
        public ActionResult Index()
        {
            if (Sessions.LoggedInUser != null)
                return View();
            else
                return RedirectToAction("Index", "Home");
        }
        #endregion

        #region ReportData

        /// <summary>
        /// Function to Show various reports to inspector
        /// </summary>
        /// <param name="inspectionOrderid"></param>
        /// <returns></returns>

        public ActionResult ReportData()
        {
            try
            {
                if (Sessions.LoggedInUser != null && Sessions.LoggedInUser.RoleName == "Property Inspector")
                {
                    string ReportType = string.Empty;

                    if (!string.IsNullOrEmpty(Request.QueryString["ReportType"].ToString()))
                        ReportType = Request.QueryString["ReportType"].ToString();

                    #region Total Sales
                    /*Report Type = Total Sales*/
                    if (ReportType == "TotalSales")
                    {
                        InspectorReport objInspectorReport = new InspectorReport();
                        List<Report> objReportTotalSales = new List<Report>();

                        objReportTotalSales = (from IO in context.InspectionOrders
                                               join IOD in context.InsectionOrderDetails
                                               on IO.InspectionOrderID equals IOD.InspectionOrderId
                                               where IO.InspectorID == Sessions.LoggedInUser.UserId
                                               join Pay in context.Payments
                                               on IO.InspectionOrderID equals Pay.ReportID
                                               select new Report
                                               {
                                                   OwnerFirstName = IOD.OwnerFirstName,
                                                   OwnerLastName = IOD.OwnerLastName,
                                                   StreetAddress = IOD.PropertyAddress,
                                                   City = IOD.PropertyAddressCity,
                                                   State = IOD.PropertyAddressState,
                                                   InspectionDate = IO.CreatedDate,
                                                   AmountReceived = Pay.PaymentAmount,
                                                   PaymentPlan = Pay.PaymentType,
                                               }).ToList();

                        objInspectorReport.ReportData = objReportTotalSales;
                        return View(objInspectorReport);
                    }
                    #endregion

                    #region Total Report Created and Inspection Reports
                    /*Report Type = Total Report Created and Inspection Reports*/
                    else if (ReportType == "TotalReportCreated" || ReportType == "InspectionReports" || ReportType == "InspectionCompleted")
                    {
                        /*Data filtered for completed report only*/
                        if (ReportType == "InspectionCompleted" || ReportType == "InspectionReports")
                        {
                            InspectorReport objInspectorReport = new InspectorReport();
                            List<Report> objListOfInspectorInspectionCompleted = new List<Report>();

                            objListOfInspectorInspectionCompleted = (from IO in context.InspectionOrders
                                                                     join IOD in context.InsectionOrderDetails
                                                                     on IO.InspectionOrderID equals IOD.InspectionOrderId
                                                                     where IO.InspectorID == Sessions.LoggedInUser.UserId && IO.InspectionStatus == "Completed"
                                                                     select new Report
                                                                     {
                                                                         OwnerFirstName = IOD.OwnerFirstName,
                                                                         OwnerLastName = IOD.OwnerLastName,
                                                                         StreetAddress = IOD.PropertyAddress,
                                                                         City = IOD.PropertyAddressCity,
                                                                         State = IOD.PropertyAddressState,
                                                                         InspectionDate = IO.CreatedDate,
                                                                         Inspectionstatus = IO.InspectionStatus,
                                                                         OrderID = IO.InspectionOrderID,
                                                                         ReportNo = IO.UniqueID
                                                                     }).ToList();

                            foreach (var item in objListOfInspectorInspectionCompleted)
                            {
                                var item1 = context.Payments.Where(x => x.ReportID == item.OrderID).ToList();
                                if (item1 != null)
                                {
                                    var Paymentplan = item1.Where(x => x.PaymentType == "HomeSeller").FirstOrDefault();
                                    if (Paymentplan != null)
                                        item.AmountReceived = context.Payments.Where(x => x.ReportID == item.OrderID).FirstOrDefault().PaymentAmount;
                                }
                            }

                            objInspectorReport.ReportData = objListOfInspectorInspectionCompleted;
                            return View(objInspectorReport);
                        }
                        else
                        {
                            InspectorReport objInspectorReport = new InspectorReport();
                            List<Report> objListOfInspectorTotalReportCreated = new List<Report>();

                            objListOfInspectorTotalReportCreated = (from IO in context.InspectionOrders
                                                                    join IOD in context.InsectionOrderDetails
                                                                    on IO.InspectionOrderID equals IOD.InspectionOrderId
                                                                    join Pay in context.Payments on IO.InspectionOrderID equals Pay.ReportID
                                                                    where IO.InspectorID == Sessions.LoggedInUser.UserId && IO.InspectionStatus == "Completed"
                                                                    select new Report
                                                                    {
                                                                        OwnerFirstName = IOD.OwnerFirstName,
                                                                        OwnerLastName = IOD.OwnerLastName,
                                                                        StreetAddress = IOD.PropertyAddress,
                                                                        City = IOD.PropertyAddressCity,
                                                                        PaymentPlan = Pay.PaymentType,
                                                                        State = IOD.PropertyAddressState,
                                                                        InspectionDate = IO.CreatedDate,
                                                                        Inspectionstatus = IO.InspectionStatus
                                                                    }).ToList();
                            objInspectorReport.ReportData = objListOfInspectorTotalReportCreated;
                            return View(objInspectorReport);
                        }
                    }
                    #endregion

                    #region Payment Reports
                    /*Report Type = Payment Reports*/
                    else if (ReportType == "PaymentReports")
                    {
                        InspectorReport objInspectorReport = new InspectorReport();
                        List<Report> objListOfInspectorPaymentReports = new List<Report>();

                        objListOfInspectorPaymentReports = (from IO in context.tblinspectionorder

SpectorMax/Views/Inspector/InspectionSchedule.cshtml
@model SpectorMax.Entities.Classes.InspectorReport

@{
    ViewBag.Title = "InspectionSchedule";
    Layout = "~/Views/Shared/_NLayout.cshtml";
}
<script>
    $(document).ready(function () {
        $("#tblinspectionDetail").dataTable();
    })

</script>
<div class="container">
    <div class="row">
        <div class="col-md-12">
           <p>&nbsp; &nbsp;</p>
        </div>
    </div>

  

    <div class="row">
        <div class="col-md-12">
            <div class="report">
                <div class="row">

                    <div class="col-md-12 space">

                        <h2>Inspection Scheduled</h2>

                    </div>
                </div>

                <div class="row">

                    <div class="col-md-12">

                        <div class="">

                            <div class="col-md-12">

                                <div class="table-responsive" id="renderRecentViewedReport">

                                    <table class="table table-striped table-bordered table-hover" id="tblinspectionDetail">
                                        <thead>
                                            <tr>
                                                <th width="18%">Address</th>
                                                <th width="18%">Owner Name</th>
                                                <th width="12%">City</th>
                                                <th width="12%">State</th>
                                                <th width="10%">Zip</th>
                                                <th>Requested Date</th>
                                                <th width="14%">Scheduled Date</th>
                                                <th width="14%">&nbsp;</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model.ReportData)
                                            {
                                                <tr>

                                                    <td>
                                                @item.StreetAddress   @item.City   @item.State   @item.Zip  
                                                    </td>
                                                    <td>@item.OwnerFirstName @item.OwnerLastName</td>
                                                    <td>@item.City</td>
                                                    <td>@item.State</td>
                                                    <td>@item.Zip</td>
                                                    <td>@item.InspectionDate.Value.ToShortDateString()</td>
                                                    <td>
                                                      @item.ScheduledDate.Value.ToShortDateString()
                                                    </td>
                                                        <td>
                                                        <a data-orderid="@item.OrderID" id="btnViewDetails" class="green-btn" role="button" href="@Url.Action("CreateNewInspection", "Inspector", new { @item.OrderID })">View Request</a></td>
                                                    

                                                   
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

</div>

SpectorMax/Views/Inspector/ReportData.cshtml
@model SpectorMax.Entities.Classes.InspectorReport
@{
    ViewBag.Title = "TotalSales";
    Layout = "~/Views/Shared/_NLayout.cshtml";
}


    @{
        string ReportType = string.Empty;

        if (!string.IsNullOrEmpty(Request.QueryString["ReportType"].ToString()))
        {
            ReportType = Request.QueryString["ReportType"].ToString();
        }

        switch (ReportType)
        {
                case "TotalSales":
                @Html.Partial("~/Views/Inspector/_PartialTotalSales.cshtml", Model);
                break;
                case "TotalReportCreated":
                @Html.Partial("~/Views/Inspector/_PartialTotalReportCreated.cshtml", Model);
                break;
                case "InspectionReports":
                @Html.Partial("~/Views/Inspector/_PartialInspectionReports.cshtml", Model);
                break;
                case "PaymentReports":
                @Html.Partial("~/Views/Inspector/_PartialPaymentReports.cshtml", Model);
                break;
                case "ArchivedReports":
                @Html.Partial("~/Views/Inspector/_PartialArchivedReports.cshtml", Model);
                break;
                 case "InspectionRequest":
                @Html.Partial("~/Views/Inspector/_PartialInspectionRequest.cshtml", Model);
                break;
                case "InspectionCompleted":
                @Html.Partial("~/Views/Inspector/_PartialInspectionReports.cshtml", Model);
                break;
                case "ReportViewed":
                 @Html.Partial("~/Views/Inspector/_PartialReportViewed.cshtml", Model);
                break;
                case "NotificationForInspector":
                @Html.Partial("~/Views/Inspector/_PartialUpdateMaintenanceRequired.cshtml", Model.objPropertyAddress);
                break;
                case "UpdateReport":
                @Html.Partial("~/Views/Inspector/_PartialUpdateRecord.cshtml", Model);
                break;
                case "ViewAndEditReport":
                 @Html.Partial("~/Views/Inspector/_PartialInspectionReports.cshtml", Model);
                break;
                default:
                break;
 
        }
    }


<script type="text/javascript">
    $(document).ready(function () {
        $("#anchorLogoImage").attr("href", $URL._InspectorDashBoard);
        $('.datepicker').datepicker({
            //format: 'mm-dd-yyyy'
            format: 'yyyy-mm-dd'
        });
    });
</script>

SpectorMax/Views/Inspector/UpdateRepot.cshtml
@model List<SpectorMax.Entities.Classes.PropertyAddress>

@{
    ViewBag.Title = "UpdateRepot";
    Layout = "~/Views/Shared/_NLayout.cshtml";
}

<script>
    $(document).ready(function () {
        $("#tblUpdateReport").dataTable();
        $("#tblUpdateReport tr .green-btn").click(function () {
            var orderid = $(this).attr("data-orderid");
            $(location).attr("href", $URL._ViewDetailReport + "?inspectionOrderId=" + orderid)

        })
        $("#tblUpdateReport tr .blu-btn").click(function () {
            var Reportid = $(this).attr("data-orderid");
            //var Reportid = $(this).attr("data-ReportId");
            $(location).attr("href", $URL._ViewComprehensiveReport + "?inspectionOrderId=" + Reportid)

        })
    });

</script>
<div class="container">
      <div class="row">
        <div class="col-md-12">
            <p class="welcome">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="report">
                <div class="row">

                    <div class="col-md-12 space">

                        <h2>Update Report (s)</h2>

                    </div>
                </div>

                <div class="row">

                    <div class="col-md-12">

                        <div class="">

                            <div class="col-md-12">

                                <div class="table-responsive" id="renderRecentViewedReport">

                                    <table class="table table-striped table-bordered table-hover" id="tblUpdateReport">
                                        <thead>
                                            <tr>
                                                <th width="18%">Report No</th>
                                                <th width="12%">&nbsp;</th>
                                                <th width="18%">&nbsp;</th>
                                                <th width="12%">Address</th>
                                                <th width="10%">City</th>
                                                <th>State</th>
                                                <th width="14%">Zip</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr>

                                                    <td>@item.ReportNo  </td>
                                                    <td> <button type="button" id="btnTakeAction" data-orderid="@item.OrderID" class="blu-btn">View</button></td>
                                                    <td><button type="button"  data-orderid="@item.OrderID" id="btnApprove" class="green-btn" >Approve Update</button></td>
                                                    <td>@item.StreetAddress</td>
                                                    <td>@item.City</td>
                                                    <td>@item.State</td>
                                                    <td>
                                                       @item.Zip
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

</div>

SpectorMax/Views/Inspector/_ManageCommentLibrary.cshtml
@model SpectorMax.Entities.Classes.CommentLibrary
@*@using SpectorMax.Entities.Classes*@
@{    
    string AdminCommentLibraryID = "";
    string txtBoxComment = "";
}

<link href="@Url.Content("~/Content/TablesCss/demo_page.css")" rel="stylesheet">
<link href="@Url.Content("~/Content/TablesCss/header.ccss.css")" rel="stylesheet">
<link href="@Url.Content("~/Content/TablesCss/demo_table.css")" rel="stylesheet">

@*<script src="@Url.Content("~/Scripts/jquery.js")" type="text/javascript"></script>*@
<script src="@Url.Content("~/Scripts/jquery.dataTables.js")" type="text/javascript"></script>


<script>
    $(document).ready(function () {
        $("#CommentTable").dataTable({
            "bPaginate": false,
            "bLengthChange": false,
            "bFilter": false, "bInfo": false,
        });

        $("#CommentTable input[type=checkbox]").click(function () {
            if ($("#CommentTable input[type=checkbox]:checked").length == 0) {
                $("#btnSaveSelection").prop("disabled", true);
            } else {
                $("#btnSaveSelection").prop("disabled", false);
            }
        })
    });
    $(".Edits").click(function () {
        $(this).css("display", "none");
        $(this).parent('td').find('.Deletes').css("display", "none");
        $(this).parent('td').find('.Cancels').css("display", "inline-table");
        $(this).parent('td').find('.Updates').css("display", "inline-table");
        $(this).parents('td:first').prev('td').find('.Comment').css("display", "block")
        $(this).parents('td:first').prev('td').find('.ComentHref').css("display", "none")
    });
    $(".Cancels").click(function () {
        $(this).css("display", "none");
        $(this).parent('td').find('.Updates').css("display", "none");

        $(this).parent('td').find('.Deletes').css("display", "inline-table");
        $(this).parent('td').find('.Edits').css("display", "inline-table");

        $(this).parents('td:first').prev('td').find('.Comment').css("display", "none")
        $(this).parents('td:first').prev('td').find('.ComentHref').css("display", "block")
    });
</script>



<table id="CommentTable" class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th id="headSelectComment" class="headSelectComment" style="width: 10%; display: none"></th>
            <th style="width: 50%">Comment Text</th>
            <th style="width: 40%">Action</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.AdminCommanLibrary.Count > 0)
        {
            foreach (var items in Model.AdminCommanLibrary)
            {
            
            <tr>
                @if (items.IsSelected == true)
                {
                    <td style="display: none" class="chkSelectComment" id="chkSelectComment">
                        <input type="checkbox" checked="checked" class="checkbox" id="chkSelect" data-itemid="@items.Id" />
                    </td>
                }
                else
                {
                    <td style="display: none" class="chkSelectComment" id="chkSelectComment">
                        <input type="checkbox" class="checkbox" id="chkSelect" data-itemid="@items.Id" />
                    </td>
                }
                <td>
                    <label class="ComentHref" style="width: 410px;">@items.CommentText</label>
                    @*<a href="#" class="ComentHref" id="CommentText" style="width:450px;" >@items.CommentText</a>*@
                    <textarea class="Comment"  style="width:430px; font-family:arial; display:none;" id="@items.Id">@items.CommentText</textarea>
                </td>
                @if (Convert.ToBoolean(items.IsAdminComment) == false)
                {
                    <td>
                        <button id="btnEdit" class="Edits btn btn-primary btn-xs" data-ItemId="@items.Id">Edit</button>
                        <button  id="btnUpdate" class="Updates btn btn-primary btn-xs" onclick="UpdateDelete(this,'update','@items.Id')" style="display:none;">Update</button>
                        <button id="btnCancel" class="Cancels btn btn-primary btn-xs" onclick="Cancel(@items.Id)" style="display:none;">Cancel</button>
                        <button id="btnDelete" class="Deletes btn btn-primary btn-xs" onclick="UpdateDelete(this,'delete','@items.Id')">Delete</button>
                    </td>
                }
                else
                {
                    <td>&nbsp;
                    </td>
                }

            </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="4" style="text-align: center; color: red;" class="bod_rgt">No record found</td>
            </tr>
        }
    </tbody>
</table>

SpectorMax/Views/Inspector/_PartialArchivedReports.cshtml
@model SpectorMax.Entities.Classes.InspectorReport 

<script type="text/javascript">
    $(document).ready(function () {
        $("#anchorLogoImage").attr("href", $URL._InspectorDashBoard);
        $("#tblinspectionDetail").dataTable();

        $("#btnSearch").click(function () {
            if ($("#txtFromDate").val() != "" && $("#txtTodate").val() != "") {
                var fromdate = $("#txtFromDate").val().replace(/\-/g, '');
                var todate = $("#txtTodate").val().replace(/\-/g, '');
                if (todate < fromdate) {
                    ShowAlertMessage("title", "ToDate must be greater than or equal to FromDate");
                    return false;
                }
            }
            $.ajax({
                type: "Post",
                url: $URL._FilterInsReportData,
                data: {
                    ReportType: "ArchivedReports",
                    startDate: $("#txtFromDate").val(),
                    endDate: $("#txtTodate").val()
                },
                dataType: "Json",
                success: function (result) {
                    if (result.Message == "logoff") {
                        $(location).attr("href", $URL._HomePage);
                    }
                    else {
                        $("#container").html(result.Result);
                        //                    
                        $("#anchorLogoImage").attr("href", $URL._InspectorDashBoard);
                        $('.datepicker').datepicker({
                            format: 'yyyy-mm-dd'
                        });
                        //
                    }
                }
            });
        });
    });
</script>
<section class="payment">
        <h2>Archived Reports</h2>
        <section class="tbl_content">
            <form id="InspectionList">
                <table width="60%" style="margin:10px" cellspacing="0">
                    <tr>
                        <td>
                            <label>From:</label></td>
                        <td>
                            @Html.TextBoxFor(model => model.fromandtodate.fromdate, new { @id = "txtFromDate", @class = "datepicker", @readonly = "readonly" })
                            @Html.ValidationMessageFor(model => model.fromandtodate.fromdate)
                        </td>
                        <td></td>
                        <td>
                            <label>To:</label></td>
                        <td>
                        @Html.TextBoxFor(model => model.fromandtodate.todate, new { @id = "txtTodate", @class = "datepicker", @readonly = "readonly" })
                        @Html.ValidationMessageFor(model => model.fromandtodate.todate)
                        <td>
                            <input type="button" class="btn" id="btnSearch" value="Search" /></td>
                    </tr>
                </table>
            </form>

            <table style="width: 100%; float: left" cellpadding="0" cellspacing="0" border="0" class="table" id="tblinspectionDetail">
                
                <thead>
                    <tr>
                        <th width="25%" class="tbl_head bod_rgt">Property Address</th>
                        <th width="20%" class="tbl_head bod_rgt">Inspection Date</th>
                        <th width="20%" class="tbl_head bod_rgt">Owner Name</th>
                        <th width="20%" class="tbl_head bod_rgt"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.ReportData)
                    {
                        <tr>
                            <td class="bod_rgt">@item.StreetAddress   @item.City   @item.State   @item.Zip  </td>
                            <td class="bod_rgt">@item.InspectionDate.Value.ToShortDateString()</td>
                            <td class="bod_rgt">@item.OwnerFirstName @item.OwnerLastName</td>
                            <td data-orderid="@item.OrderID" class="bod_rgt"><a id="Detail" href="javascript://void(0);">View Details</a></td>
                        </tr>
                    }
                <tbody>
            </table>
        </section>
        <section class="clr"></section>
    </section>