SpectorMax/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SpectorMax.Entities.Classes;
using SpectorMaxDAL;
using SpectorMax.Models;
using System.Drawing;
using System.IO;
using System.Data;
using MySql.Data.MySqlClient;
using System.Transactions;

namespace SpectorMax.Controllers
{
    public class ReportController : BaseController
    {

        #region Global Variables

        private SpectorMaxContext context = new SpectorMaxContext();
        MessageToShow _messageToShow = new MessageToShow();
        int ImageCount;
        int skip;
        int TakeImg;
        //List<string> mainSectionList = new List<string>();
        //List<string> subSectionList = new List<string>();

        string connectionstring = System.Configuration.ConfigurationManager.ConnectionStrings["SpectorMaxConnectionString"].ConnectionString;

        #endregion

        #region Index
        //
        // GET: /Report/

        public ActionResult Index()
        {
            try
            {
                if (Sessions.LoggedInUser != null)
                {
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }

            }
            catch (Exception ex)
            {

                throw ex;
            }

        }
        #endregion

        #region ViewDetailReport
        /// <summary>
        /// GET:// Method for get detail report aginst inspection order id.
        /// <param name="inspectionOrderId"></param>
        /// </summary>
        /// <returns></returns>
        public ActionResult ViewDetailReport(string inspectionOrderId, string PaymentType)
        {
            try
            {
                if (Sessions.LoggedInUser != null)
                {


                    List<SubSections> lstSubSections = new List<SubSections>();

                    var TermsAndConditions = from k in context.EmailTemplates
                                             where k.TemplateId == 26
                                             select k.TemplateDiscription;

                    ViewBag.Message = TermsAndConditions.FirstOrDefault();

                    #region SubSection

                    lstSubSections = (from IR in context.InspectionReport
                                      join SS in context.SubSections on IR.SubsectionId equals SS.ID
                                      where IR.InspectionOrderId == inspectionOrderId
                                      select new SubSections
                                      {
                                          SectionID = IR.SectionId,
                                          //SectionName = MS.SectionName,
                                          SubSectionID = IR.SubsectionId,
                                          SubSectionName = SS.SubSectionName,
                                          SortOrder = SS.SortOrder,
                                          CheckBoxID = IR.CheckboxID
                                      }).Distinct().OrderBy(x => x.SortOrder).ToList();

                    #endregion


                    #region MainSection
                    List<MainSections> lstMainSection = new List<MainSections>();

                    lstMainSection = (from IR in context.InspectionReport
                                      join MS in context.MainSections on IR.SectionId equals MS.ID
                                      where IR.InspectionOrderId == inspectionOrderId
                                      select new MainSections
                                      {
                                          SectionID = MS.ID,
                                          SectionName = MS.SectionName,
                                          SortOrder = MS.SortOrder
                                      }).Distinct().OrderBy(x => x.SortOrder).ToList();

                    #endregion
                    /*Check whether Inspection Rating is already done for this report--Start*/
                    #region Is InspectionDone
                    var IsInspectionDone = from Ratings in context.InspectorRatings
                                           where Ratings.InspectionID == inspectionOrderId
                                           select Ratings.RatingID;
                    if (IsInspectionDone.Any())
                    {
                        ViewBag.InspectionDone = "InpectionAlreadyDone";
                    }
                    else
                    {
                        ViewBag.InspectionDone = null;
                    }

                    #endregion
                    /*End*/

                    /*Get Details Report--Start*/

                    #region Get Detail Report
                    DetailsReportCommonPoco objDetailsReportCommonPoco = new DetailsReportCommonPoco();
                    ViewPreviousInspection objviewPreviousInspection = new ViewPreviousInspection();
                    List<DetailsReportCommonPoco> objReport = new List<DetailsReportCommonPoco>();
                    ViewBag.InspectionOrderId = inspectionOrderId;
                    objviewPreviousInspection = (from detail in context.tblinspectionorderdetail
                                                 join IO in context.tblinspectionorder on detail.InspectionorderdetailsID equals IO.InspectionOrderDetailId
                                                 join UI in context.UserInfoes on IO.InspectorID equals UI.ID
                                                 join ID in context.InspectorDetail on UI.ID equals ID.UserID
                                                 join PD in context.tblpropertydescription on detail.PropertyDescription equals PD.PropertyDescriptionId
                                                 join AI in context.InspectionAdditionalInfo on detail.InspectionorderdetailsID equals AI.InspectionOrderID into g
                                                 join agent in context.AgentLibraries on detail.InspectionorderdetailsID equals agent.InspectionOrderID
                                                 where detail.InspectionorderdetailsID == inspectionOrderId && agent.AgentType == "1" && IO.IsDeleted == false
                                                 select new ViewPreviousInspection
                                                 {
                                                     InspectionOrderId = inspectionOrderId,
                                                     PropertyAddress = detail.PropertyAddress,
                                                     RequestedBy = detail.RequesterFName + " " + detail.RequesterLName,
                                                     Agent = agent.AgentFirstName + agent.AgentLastName,
                                                     AgentEmail = agent.AgentEmailAddress,
                                                     AgentPhone = agent.AgentPhoneDay + " " + agent.AgentPhoneDay1,
                                                     ScheduleInspectionDate = IO.ScheduledDate,
                                                     HomeAge = detail.RoofAge,
                                                     SqureFeet = detail.SqureFootage,
                                                     ReportNumber = IO.ReportNo,
                                                     Bath = detail.Bathrooms,
                                                     Bed = detail.Bedrooms,
                                                     PropertyDescription = PD.Type,
                                                     Units = detail.Units,
                                                     Utilities = detail.EstimatedMonthlyUtilities,
                                                     RoofAge = detail.RoofAge,
                                                     Direction = detail.Directions,
                                                     AdditionAltration = detail.Additions_Alterations,
                                                     InspectorFirstName = UI.FirstName,
                                                     InspectorLastName = UI.LastName,
                                                     InspectorStreetAddress = UI.StreetAddress,
                                                     ExperienceTraining1 = ID.ExperienceTraining1,
                                                     ExperienceTraining2 = ID.ExperienceTraining2,
                                                     ExperienceTraining3 = ID.ExperienceTraining3,
                                                     Certification1 = ID.Certification1,
                                                     Certification2 = ID.Certification2,
                                                     Certification3 = ID.Certification3,
                                                     PhotoURL = ID.PhotoURL,
                                                     Email = UI.EmailAddress,
                                                     InspectorCity = UI.City,
                                                     InspectorState = UI.State,
                                                     InspectorZip = UI.ZipCode,
                                                     InspectorCountry = UI.Country,
                                                     InspectorPhone = UI.PhoneNo,
                                                     InspectorAddress1 = UI.Address,
                                                     InspectorAddress2 = UI.AddressLine2,
                                                     MainHomePage = g
                                                 }).FirstOrDefault();



                    /*End*/
                    #endregion


                    if (objviewPreviousInspection != null)
                    {

SpectorMax/Views/Report/_PartialLogin.cshtml
@model SpectorMax.Entities.Classes.LogInModel




<script>
    $(document).ready(function () {
        $('#username').keypress(function (event) {
            $("#username").removeClass("input-validation-error");
        });
        $('#pwd').keypress(function (event) {
            $("#pwd").removeClass("input-validation-error");
        });
    });

    function Submit() {

        //if ($("#usrname").val().trim().length == 0 || $("#pwd").val().trim().length == 0 && $("#paymenttype").val() == "Verification" && $("#txtVerification").val().trim().length == 0) {
        //    if ($("#usrname").val().trim().length == 0 && $("#pwd").val().trim().length == 0) {
        //        $("#txtVerification").addClass("input-validation-error");
        //        $("#usrname").addClass("input-validation-error");
        //        $("#pwd").addClass("input-validation-error");
        //    }
        //    else if ($("#usrname").val().trim().length == 0 || $("#pwd").val().trim().length == 0 && $("#paymenttype").val() != "Verification" )
        //    {
        //        $("#usrname").addClass("input-validation-error");
        //        $("#pwd").addClass("input-validation-error");
        //    }
        //    else if ($("#pwd").val().trim().length == 0) {
        //        $("#pwd").addClass("input-validation-error");
        //    }
        //    else if ($("#paymenttype").val() == "Verification" && $("#txtVerification").val().trim().length == 0) {
        //        $("#txtVerification").addClass("input-validation-error");
        //    }
        //    else {
        //        $("#usrname").addClass("input-validation-error");
        //    }
        //} 
        var isValid = true;
        $('#PartialLogin .main').each(function () {
            if ($.trim($(this).val()) == '') {
                isValid = false;
                //$(this).css({
                //    "border": "1px solid red",
                //    "background": "#FFCECE"
                //});
                $(this).addClass("input-validation-error")
            }
            else {
                $(this).removeClass("input-validation-error")
                //$(this).css({
                //    "border": "",
                //    "background": ""
                //});
            }
        });
        //if ($("#paymenttype").val() == "Verification" && $("#txtVerification").val().trim().length == 0) {

        //    $("#txtVerification").addClass("input-validation-error")
        //    isValid = false;
        //    //  e.preventDefault();
        //}
        //else if(isValid && $("#paymenttype").val() != "Verification") {

        //    $("#txtVerification").removeClass("input-validation-error")
        //    isValid = true;
        //    //  e.preventDefault();
        //}
        //alert(isValid)
        if (isValid) {
            var ReportId = GetQueryStringParams('UniqueId')
            showLoader();
            $.ajax({
                type: "POST",
                url: '@Url.Action("UserLogin", "UserInfoes")',
                dataType: "html",
                data: {
                    UserName: $("#usrname").val(), Password: $("#pwd").val(), paymentamount: $("#amount").val(), typePayment: $("#paymenttype").val(), UniqueId: ReportId
                },
                success: function (result) {
                    var aa = JSON.parse(result)
                    if (aa.Message == "Verification")
                    {
                        $(location).attr('href', '@Url.Action("BuyUpdatableReport", "Payments")' + "?OrderId=" + aa.Result);
                        
                    }
                   else if (aa.Message == "FreeBasicReport") {
                        $(location).attr('href', '@Url.Action("SampleInspectionReportSeller", "Report")' + "?orderid=" + aa.Result);
                     }
                   else if (aa.Message == "ViewReport") {
                       $(location).attr('href', '@Url.Action("ViewComprehensiveReport", "Report")' + "?inspectionOrderId=" + aa.Result);
                    }
                   else if(aa.Message == "UpdateReport") {
                       $(location).attr('href', '@Url.Action("ViewDetailReport", "Report")' + "inspectionOrderId=" + aa.Result);
                   }
                   else if (aa.Message == "PropertyInspector") {
                       $(location).attr('href', '@Url.Action("InspectorDashboardNew", "UserInfoes")');
                   }
                   else if (aa.Message == "Admin") {
                       $(".bs-exampleExp1").show();
                       $("#SucessExp1").hide();
                       $("#lblErrorExp1").html("You are not authorized to login.");
                       hideLoader();
                   }
                   else {
                       $("#SucessExp1").hide();
                       $(".bs-exampleExp1").show();
                       $("#lblErrorExp1").html("Username or password is wrong.");
                       hideLoader();
                   }
                    //var aa = JSON.parse(result)
                    //if (aa.Result != null) {
                    //    var url = aa.Result.split("#$%DE")
                    //}
                    //if (aa.Message == "Payment") {
                    //    $(location).attr('href', $URL._PaymentPost + "?userid=" + url[0] + "&userRoleId=" + url[1] + "&amount=" + url[2] + "&amountDescription=" + url[3] + "&paymentType=" + url[4] + "&inspectionOrderId=" + url[5] + "&Validity=" + url[6]);
                    //}
                    //else if (aa.Message == "SiteUser") {

                    //}
                    //else if (aa.Message == "Property Inspector") {
                    //    $(location).attr('href', $URL._InspectorDashBoardNew);
                    //}
                    //else if (aa.Message == "ViewReport") {
                    //    $(location).attr('href', $URL._ViewReport + "?inspectionOrderId=" + url[0] + "&PaymentType=PaymentPlan");
                    //    //return RedirectToAction("ViewDetailReport", "Report", new { inspectionOrderId = Orderid, PaymentType = "PaymentPlan" });
                    //}
                    //else if (aa.Message == "Invalid email or password") {
                    //    $("#Zip-errorLogin").css("display", "block")
                    //    $("#lblMessageziperrorLogin").html("Invalid email or password");
                    //    hideLoader();
                    //}
                    //else if (aa.Message == "You are not assigned to any role. Please contact to your Administrator.") {
                    //    $("#Zip-errorLogin").css("display", "block")
                    //    $("#lblMessageziperrorLogin").html("You are not authorised.");
                    //    hideLoader();
                    //}
                    //else if (aa.Message == "FreeBasicReport") {
                    //    $(location).attr('href', $URL._FreeBasicReport + "?orderid=" + url[1]);
                    //    hideLoader();
                    //}
                    // alert(JSON.parse(result.responseText).Message)

                },
                error: function (e) {
                },
            });
        }
    }
    function DisplayErroMessage() {
        $(".field-validation-error").closest("li").each(function () {
            $(this).find(".form").live("mouseover", function () {
                $(this).find(".field-validation-error .input-validation-error").attr("style", "display:block !important");
            });
            $(this).find(".form").live("mouseout", function () {
                $(this).find(".field-validation-error .input-validation-error").attr("style", "display:none !important");
            });
        });
    }
    function GetQueryStringParams(sParam) {
        var sPageURL = window.location.search.substring(1);
        var sURLVariables = sPageURL.split('&');
        for (var i = 0; i < sURLVariables.length; i++) {
            var sParameterName = sURLVariables[i].split('=');
            if (sParameterName[0] == sParam) {
                return sParameterName[1];
            }
        }
    }

</script>
  <div class="bs-exampleExp1" style="display: none">
                    <div class="alert alert-danger alert-error">

                        <strong>Error!</strong>
                        <label id="lblErrorExp1">There might be some problem. Please try after some time.</label>
                    </div>
                </div>

                <div class="alert alert-warning" id="SucessExp1" style="display: none; margin-top: 22px;">



                    <strong>Success!</strong> Payment done successfully. Please wait while you are redirecting to comprehensive report 

                </div>
@using (Html.BeginForm("LogOn", "UserInfoes", FormMethod.Post, new { id = "PartialLogin", @class = "form-horizontal" }))
{
   @* <div class="form-group Verification">
        <label class="col-sm-4 control-label">Verification No*</label>
        <div class="col-sm-8">
            <input type="text" id="txtVerification" title="Verification Number" class="form-control" placeholder="Enter Verification No" />

        </div>
    </div>*@
     
    <div class="form-group">
        <label class="col-sm-4 control-label">User Name*</label>
        <div class="col-sm-8">
            <input type="text" id="usrname" title="Your Email" class="form-control main" placeholder="User Name" />

        </div>
    </div>
           
    <div class="form-group">
        <label class="col-sm-4 control-label">Password*</label>
        <div class="col-sm-8">
            <input type="password" id="pwd" title="Your Password" class="form-control main" placeholder="Password" />
        </div>
    </div>

    <div class="form-group">
        <div class=" col-sm-12">

            <input type="button" id="btnLogin" class="green-btn pull-right" onclick="Submit();" value="Login">
            @Html.HiddenFor(x => x.paymentamount)
            @Html.HiddenFor(x => x.typePayment)
            @Html.HiddenFor(model => model.Validity)
        </div>
    </div>
    <div class="form-group">
       
        <div class="col-sm-4">

          
        </div>
           <div class="col-sm-8">

               <a   href="@Url.Action("ForgotPassword", "UserInfoes")" role="button" data-toggle="modal">Forgot username or password?</a>
        </div>
    </div>
          
}

SpectorMax/Views/Report/_PartialRegistration.cshtml
@model SpectorMax.Entities.Classes.CreateBuyer





@using SpectorMax.Entities.Classes
<div class="bs-exampleExp" style="display: none">
    <div class="alert alert-danger alert-error">

        <strong>Error!</strong>
        <label id="lblErrorExp">There might be some problem. Please try after some time.</label>
    </div>
</div>

<div class="alert alert-warning" id="SucessExp" style="display: none; margin-top: 22px;">



    <strong>Success!</strong>< Payment done successfully. Please wait while you are redirecting to comprehensive report 

</div>

@using (Ajax.BeginForm("CreateUser", "UserInfoes", FormMethod.Post, new AjaxOptions { OnBegin = "showLoader", OnComplete = "DisplayMsg" }, new { id = "Registration1", @class = "form-horizontal" }))
{

    <div class="form-group">
        <label class="col-sm-4 control-label">Card Holder Name*</label>
        <div class="col-sm-8">
            @Html.HiddenFor(model => model.amount)
            @Html.HiddenFor(model => model.paymenttype)
            @Html.HiddenFor(model => model.OrderId)
            @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control", placeholder = "As it appears on card" })
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-4 control-label">Billing Address*</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" placeholder="Street Address">
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-4 control-label">State*</label>
        <div class="col-sm-8">
            <div class="row">




                <div class="col-md-6 col-sm-6">

                    @Html.DropDownListFor(model => model.StateId, (IEnumerable<SelectListItem>)ViewBag.StateList, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.StateId)

                </div>


                <div class="col-md-6 col-sm-6">

                    @Html.DropDownListFor(model => model.CityId, (IEnumerable<SelectListItem>)ViewBag.CityList, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CityId)
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-4 control-label">Zip*</label>
        <div class="col-sm-8">
            @Html.DropDownListFor(model => model.ZipCode, (IEnumerable<SelectListItem>)ViewBag.ZipList, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ZipCode)
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-4 control-label">Email*</label>
        <div class="col-sm-8">

            @Html.TextBoxFor(model => model.EmailAddress, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.EmailAddress)
        </div>
    </div>



    <div class="form-group">
        <label class="col-sm-4 control-label">Card Number*</label>
        <div class="col-sm-8">

            @Html.TextBoxFor(model => model.cardNumber, new { @class = "form-control", @onfocus = "if (this.value==this.defaultValue) this.value = ''", @onblur = "if (this.value=='') this.value = this.defaultValue", @MaxLength = 16 })
            @Html.ValidationMessageFor(model => model.cardNumber)
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-4 control-label">Expiration Date*</label>
        <div class="col-sm-8">
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    @Html.DropDownListFor(model => model.expiryMonth, (SelectList)ViewBag.Month, "Select Month", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.expiryMonth)

                </div>
                <div class="col-md-6 col-sm-6">
                    @Html.DropDownListFor(model => model.expiryYear, (SelectList)ViewBag.Year, "Select Year", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.expiryYear)

                </div>
            </div>
        </div>
    </div>


    <div class="form-group">
        <label class="col-sm-4 control-label">Security Code*</label>
        <div class="col-sm-8">
            <div class="row">
                <div class="col-md-7 col-sm-7">

                    @Html.TextBoxFor(model => model.securityCode, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.securityCode)
                </div>

                <div class="col-md-5 col-sm-5">
                    <label><a href="#" id="whatCvv" data-toggle="modal" data-target="#modalWhatisthis">What is this?</a></label>
                </div>

            </div>
        </div>
    </div>


    <div class="form-group">
        <div class="col-sm-12">
            <div class="checkbox">
                <label>
                    <input type="checkbox" id="chkTerms">
                    I agree to the spectormax <a href="#!" onclick="ClkTermsConditions();" id="TermsConditions">Terms & Conditions </a>of use.
                </label>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class=" col-sm-12">
            <div class="checkbox">
                <label>
                    <input type="checkbox" id="chkHomeInspections">
                    I agree to the spectormax <a href="#!" onclick="ClkHomeInspectionUserAgreementJson();" id="UserAgreement">Home Inspection User Agreement.</a>
                </label>
            </div>
        </div>
    </div>

    <div class="form-group" id="divTwoMonthMembership" style="display: none">
        <div class=" col-sm-12">
            <div class="checkbox">
                <label>
                    <input type="checkbox" id="chkTwoMonth">I agree to the spectormax <a href="#" data-toggle="modal" data-target="#modalMembershipAgreement" id="MembershipAgreement">Two Month  Membership Agreement.</a>
                </label>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class=" col-sm-10">
            <button type="submit" class="buynow" id="create">BUY NOW</button>
        </div>
    </div>


    @*<div class="form-group">
        <div class=" col-sm-12">
            <div class="checkbox">
                <label>
                    <input type="checkbox" checked="checked">
                </label>
            </div>
        </div>
    </div>*@

    <div class="form-group">

        <div class="col-sm-12">

            <p>
                From time to time Spectormax will offer our customers helpful tips
and information tips to guide them throughing the buying and 
selling process. Spectormax does not provide personal information
to any third parties. To learn more about our committment to your
policy, please refer to our  <a onclick="ClkPrivacyPolicy();" href="#!">Privacy Policy</a>.
            </p>

        </div>

    </div>


}



<!-- Modal 1 -->
<div class="modal fade" id="modalterms" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close custmclose" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title text-center" id="myModalLabel">Terms and condition</h4>
            </div>
            <div class="modal-body">
                <p>When we purchase our single comprehensive Report Plan you get the following:</p>
                <p>1. Unlimited online access to your report for upto 60 days after purchase</p>
                <p>2. Online access with upto three devices that are owned by you </p>
                <p>3. Get 100% credit from this purchase plan when you upgrade to our 2-Month &nbsp; Unlimited membership Plan</p>
                <p>Suject to our Terms & Conditions of services.</p>
            </div>

        </div>
    </div>
</div>
<!-- Modal 1 -->


<!-- Modal 2 -->
<div class="modal fade" id="modalHomeAgreement" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close custmclose" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title text-center" id="myModalLabel">Home Inspection User Agreement</h4>
            </div>
            <div class="modal-body">
                <p>When we purchase our single comprehensive Report Plan you get the following:</p>
                <p>1. Unlimited online access to your report for upto 60 days after purchase</p>
                <p>2. Online access with upto three devices that are owned by you </p>
                <p>3. Get 100% credit from this purchase plan when you upgrade to our 2-Month &nbsp; Unlimited membership Plan</p>
                <p>Suject to our Terms & Conditions of services.</p>
            </div>

        </div>
    </div>
</div>
<!-- Modal 2 -->


<!-- Modal 3 -->
<div class="modal fade" id="modalMembershipAgreement" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close custmclose" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title text-center" id="myModalLabel">Two Month Membership Agreement.</h4>
            </div>
            <div class="modal-body">
                <p>When we purchase our single comprehensive Report Plan you get the following:</p>
                <p>1. Unlimited online access to your report for upto 60 days after purchase</p>
                <p>2. Online access with upto three devices that are owned by you </p>
                <p>3. Get 100% credit from this purchase plan when you upgrade to our 2-Month &nbsp; Unlimited membership Plan</p>
                <p>Suject to our Terms & Conditions of services.</p>
            </div>

        </div>
    </div>
</div>
<!-- Modal 3 -->

<!-- Modal 4 -->
<div class="modal fade" id="modalWhatisthis" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close custmclose" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title text-center" id="myModalLabel">What is cvv?</h4>
            </div>
            <div class="modal-body">
                <p>When we purchase our single comprehensive Report Plan you get the following:</p>
                <p>1. Unlimited online access to your report for upto 60 days after purchase</p>
                <p>2. Online access with upto three devices that are owned by you </p>
                <p>3. Get 100% credit from this purchase plan when you upgrade to our 2-Month &nbsp; Unlimited membership Plan</p>
                <p>Suject to our Terms & Conditions of services.</p>
            </div>

        </div>
    </div>
</div>
<!-- Modal 4 -->