SpectorMax/Controllers/InspectorRatingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SpectorMaxDAL;
using SpectorMax.Models;
using SpectorMax.Entities.Classes;
using System.Data.Objects;

namespace SpectorMax.Controllers
{
    public class InspectorRatingsController : BaseController
    {
        private SpectorMaxContext context = new SpectorMaxContext();
        MessageToShow _MessageToShow = new MessageToShow();
        //
        // GET: /InspectorRatings/

        public ViewResult Index(FormCollection form)
        {
              try
                {

                    if (Sessions.LoggedInUser != null)
                    {
                        int? zipcode;
                        InspectorRatingPoco objInspectorRatingPocoPoco;
                        ViewBag.Message = null;
                        List<InspectorRatingPoco> ListofRatingDetails = new List<InspectorRatingPoco>();
                        if (Sessions.LoggedInUser.RoleName == "Property Inspector")
                        {
                            var RatingList = context.InspectorRatings.ToList().Where(x => x.InspectorID == Sessions.LoggedInUser.UserId).ToList();
                            if (RatingList.Count > 0)
                            {
                                foreach (var item in RatingList)
                                {
                                    objInspectorRatingPocoPoco = new InspectorRatingPoco();
                                    objInspectorRatingPocoPoco.rating = item.Rating1;
                                    objInspectorRatingPocoPoco.Comment = item.Comment;
                                    objInspectorRatingPocoPoco.ratingID = item.RatingID;
                                    objInspectorRatingPocoPoco.IsRequestedtoRemove = item.RequestedtoRemove;
                                    userinfo objratingBy = context.UserInfoes.Where(x => x.ID == item.RatingByID).ToList().FirstOrDefault();
                                    if (objratingBy != null)
                                    {
                                        objInspectorRatingPocoPoco.ratingBy = objratingBy.FirstName + " " + objratingBy.LastName + " From " + objratingBy.City + "," + objratingBy.State + " On " + item.CreatedDate.Value.ToShortDateString(); ;
                                        ListofRatingDetails.Add(objInspectorRatingPocoPoco);
                                    }
                                }
                            }
                            else
                            {
                                //string InpectorName = context.UserInfoes.Where(x => x.ZipCode == zipcode && x.Role == "85DA6641-E08A-4192-A").FirstOrDefault().FirstName;
                                ViewBag.Message = "No ratings assigned ";
                            }
                            return View(ListofRatingDetails);
                        }
                        else
                        {

                            if (form.Count > 0)
                            {

                                zipcode = Convert.ToInt32(form[0]);


                                //Convert.ToInt32(form.Get("txtSearchLocation"));
                                bool IsExist = false;
                                //List<UserInfo> UserinZipCode = context.ZipCode.Where(x => x.Zip == zipcode).ToList();
                                IsExist = context.ZipCodeAssigned.Any(x => x.ZipCode == zipcode);

                                //IsExist = UserinZipCode.Any(x => x.Role == "85DA6641-E08A-4192-A");

                                if (IsExist == true)
                                {
                                    string userid = context.ZipCodeAssigned.Where(x => x.ZipCode == zipcode).FirstOrDefault().InspectorID;

                                    #region Inspector Details
                                    userinfo objuserinfo = new userinfo();
                                    InspectorDetails objInspectorDetail = new InspectorDetails();
                                    objuserinfo = context.UserInfoes.Where(x => x.ID == userid).FirstOrDefault();
                                    objInspectorDetail.FirstName = objuserinfo.FirstName;
                                    objInspectorDetail.LastName = objuserinfo.LastName;
                                    objInspectorDetail.Address = objuserinfo.Address;
                                    objInspectorDetail.Address2 = objuserinfo.AddressLine2;
                                    objInspectorDetail.State = objuserinfo.State;
                                    objInspectorDetail.StreetAddress = objuserinfo.StreetAddress;
                                    objInspectorDetail.City = objuserinfo.City;
                                    objInspectorDetail.Country = objuserinfo.Country;
                                    objInspectorDetail.EmailAddress = objuserinfo.EmailAddress;
                                    objInspectorDetail.dateofbirth = objuserinfo.DateOfBirth;
                                    objInspectorDetail.PhoneNo = objuserinfo.PhoneNo;
                                    var inspectorDetail = context.InspectorDetail.FirstOrDefault(x => x.UserID == userid);
                                    if (inspectorDetail != null)
                                    {
                                        objInspectorDetail.PhotoURL = inspectorDetail.PhotoURL;
                                        objInspectorDetail.ExperienceTraining1 = inspectorDetail.ExperienceTraining1;
                                        objInspectorDetail.ExperienceTraining2 = inspectorDetail.ExperienceTraining2;
                                        objInspectorDetail.ExperienceTraining3 = inspectorDetail.ExperienceTraining3;
                                        objInspectorDetail.Certification1 = inspectorDetail.Certification1;
                                        objInspectorDetail.Certification2 = inspectorDetail.Certification2;
                                        objInspectorDetail.Certification3 = inspectorDetail.Certification3;

                                    }
                                    else
                                    {
                                        objInspectorDetail.PhotoURL = "";
                                        objInspectorDetail.ExperienceTraining1 = "";
                                        objInspectorDetail.ExperienceTraining2 = "";
                                        objInspectorDetail.ExperienceTraining3 = "";
                                        objInspectorDetail.Certification1 = "";
                                        objInspectorDetail.Certification2 = "";
                                        objInspectorDetail.Certification3 = "";

                                    }

                                    #endregion


                                    objInspectorRatingPocoPoco = new InspectorRatingPoco();
                                    objInspectorRatingPocoPoco.Inspector = objInspectorDetail;
                                    var RatingList = context.InspectorRatings.ToList().Where(x => x.InspectorID == userid).ToList();
                                    if (RatingList.Count > 0)
                                    {
                                        foreach (var item in RatingList)
                                        {
                                            // objInspectorRatingPocoPoco = new InspectorRatingPoco();
                                            objInspectorRatingPocoPoco.rating = item.Rating1;
                                            objInspectorRatingPocoPoco.Comment = item.Comment;
                                            objInspectorRatingPocoPoco.ratingID = item.RatingID;
                                            objInspectorRatingPocoPoco.IsRequestedtoRemove = item.RequestedtoRemove;
                                            userinfo objratingBy = context.UserInfoes.Where(x => x.ID == item.RatingByID).ToList().FirstOrDefault();
                                            if (objratingBy != null)
                                            {
                                                objInspectorRatingPocoPoco.ratingBy = objratingBy.FirstName + " " + objratingBy.LastName + " From " + objratingBy.City + "," + objratingBy.State + " On " + item.CreatedDate.Value.ToShortDateString(); ;
                                                ListofRatingDetails.Add(objInspectorRatingPocoPoco);
                                            }
                                        }
                                    }
                                    else
                                    {
                                        ViewBag.Message = "NO RATINGS ASSIGNED YET";
                                        objInspectorRatingPocoPoco.Inspector = objInspectorDetail;
                                        ListofRatingDetails.Add(objInspectorRatingPocoPoco);
                                    }
                                }
                                else
                                {
                                    ViewBag.Message = "NO INSPECTOR IS EXIST ON THIS ZIPCODE";
                                }
                            }
                            else
                            {
                                ViewBag.Message = "NO INSPECTOR IS EXIST ON THIS ZIPCODE";
                            }
                            return View(ListofRatingDetails);
                        }
                    }
                    else
                    {
                        return View("~/Views/Home/Index.cshtml");
                    }
                }
                catch (Exception ex)
                {
                    throw ex;
                }
           
        }

SpectorMax/Views/UserInfoes/ConfirmEmail.cshtml
@{
    ViewBag.Title = "ConfirmEmail";
    Layout = @Url.Content("~/Views/Shared/HomeLayout.cshtml"); ;
}
@if (ViewBag.message != string.Empty && @ViewBag.message == "Confirmed")
{
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="welcome">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">

                <h1 style="color: #C60C46; font-size: 220%; line-height: 0.8; margin: 0 0 20px;">Email Confirmed</h1>
                <br />
                <p>
                    Dear
                    <label id="lblfname" style="font-weight: bold">@ViewBag.Fname</label>&nbsp;<label id="lbllname" style="font-weight: bold">@ViewBag.Lname</label>,
                </p>
                <br />
                <p><b>Your email is confirmed with spector max.</b></p>
                <br />
                <p>Please <a href="#" data-toggle="modal" data-target="#myModal2">Click here</a> to create your first inspection order with spectormax</p>
                <br />
            </div>
        </div>
    </div>
    <!-- Modal 2 -->
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close custmclose" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title text-center" id="myModalLabel1">Login</h4>
            </div>
            <div class="modal-body">
                <div class="bs-exampleExp" style="display: none">
                    <div class="alert alert-danger alert-error">
                        <strong>Error!</strong>
                        <label id="loginmessage">There might be some problem. Please try after some time.</label>
                    </div>
                </div>
                <form id="formLogin" class="form">
                    <label>Login</label>
                    <input id="username1" type="text" required="" style="width: 260px;" class="form-control" title="Enter your username" data-valid-min="6" pattern="^[a-z,A-Z,0-9,_]{6,15}$" placeholder="Username" name="username">
                    <input id="password1" type="password" required="" style="width: 260px; margin-top: 3px;" class="form-control" title="Enter your password" placeholder="Password" name="password">

                    <br>
                    <button id="btnLogin1" class="rate tpbm has-spinner" type="button">
                        <span class="spinner"><i class="icon-spin icon-spinner icon-large"></i></span>
                        Login</button>

                    @*<img alt="progress bar" style="display:none" id="loginProgress" src="@Url.Content("~/Images/loading_icon.gif")" />*@
                </form>

                <form>
                    <a id="btnNewUser1" data-target="#formRegister" data-toggle="collapse" title="Fast and free sign up!" href="@Url.Action("create", "UserInfoes")">New User? Sign-up..</a>
                </form>
                <form>
                    <a href="@Url.Action("ForgotPassword", "UserInfoes")" role="button" data-toggle="modal">Forgot username or password?</a>
                </form>
                <form>
                    <a href="@Url.Action("Contact", "Home")" role="button" data-toggle="modal">
                        <small>Need help? Contact us</small>
                    </a>
                </form>

            </div>
        </div>
    </div>
</div>

<!-- Modal 2 -->
    
}
else
{
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="welcome">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">

                <h1 style="color: #C60C46; font-size: 220%; line-height: 0.8; margin: 0 0 20px;">Email Not Confirmed</h1>
                <br />

                <p><b>Your email is not confirmed with spector max. There might be some problem with your account.</b></p>
                <br />
              
            </div>
        </div>
    </div>
}

<script>
    $(document).ready(function () {
        $("#btnLogin1").click(function () {
            $("#btnLogin1").addClass('active');

            $.ajax({
                type: "POST",
                url: '@Url.Action("JSONLogOn", "UserInfoes")',
                dataType: "html",
                data: {
                    UserName: $("#username1").val(),
                    Password: $("#password1").val(),
                    rememberme: true
                },
                success: function (result) {
                    $("#btnLogin1").removeClass('active');
                    var msg = JSON.parse(result);
                    if (msg.UserRoleType == "Property Inspector") {
                        var url = '@Url.Action("InspectorDashboardNew", "UserInfoes")';
                        window.location.href = url;
                    }
                    else if (msg.UserRoleType == "SiteUser") {
                        var url = '@Url.Action("NCreateNewInspection", "NInspectionOrderDetails")';
                        window.location.href = url;
                    }

                    else {
                        $("#loginmessage").html(msg.Message);
                        $(".bs-exampleExp").css("display", "block")
                    }
                },
                error: function (e) {
                    $("#btnLogin1").removeClass('active');
                },
            });
        });
    });

</script>

SpectorMax/Views/UserInfoes/Details.cshtml
@model SpectorMaxDAL.UserInfo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>UserInfo</legend>

    <div class="display-label">EmailAddress</div>
    <div class="display-field">@Model.EmailAddress</div>

    <div class="display-label">Password</div>
    <div class="display-field">@Model.Password</div>

    <div class="display-label">Role</div>
    <div class="display-field">@Model.Role</div>

    <div class="display-label">FirstName</div>
    <div class="display-field">@Model.FirstName</div>

    <div class="display-label">LastName</div>
    <div class="display-field">@Model.LastName</div>

    <div class="display-label">Address</div>
    <div class="display-field">@Model.Address</div>

    <div class="display-label">StreetAddress</div>
    <div class="display-field">@Model.StreetAddress</div>

    <div class="display-label">AddressLine2</div>
    <div class="display-field">@Model.AddressLine2</div>

    <div class="display-label">State</div>
    <div class="display-field">@Model.State</div>

    <div class="display-label">City</div>
    <div class="display-field">@Model.City</div>

    <div class="display-label">Country</div>
    <div class="display-field">@Model.Country</div>

    <div class="display-label">PhoneNo</div>
    <div class="display-field">@Model.PhoneNo</div>

    <div class="display-label">DateOfBirth</div>
    <div class="display-field">@String.Format("{0:g}", Model.DateOfBirth)</div>

    <div class="display-label">IsActive</div>
    <div class="display-field">@Model.IsActive</div>

    <div class="display-label">CreatedDate</div>
    <div class="display-field">@String.Format("{0:g}", Model.CreatedDate)</div>

    <div class="display-label">ModifiedDate</div>
    <div class="display-field">@String.Format("{0:g}", Model.ModifiedDate)</div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SpectorMax/Views/UserInfoes/Edit.cshtml
@model SpectorMaxDAL.UserInfo

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>UserInfo</legend>

        @Html.HiddenFor(model => model.ID)
		@Html.Partial("_CreateOrEdit", Model)

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SpectorMax/Views/UserInfoes/NewNotification.cshtml
@model List<SpectorMax.Entities.Classes.PropertyAddress>
@{
    ViewBag.Title = "NewNotification";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script src="@Url.Content("~/Scripts/jquery.blockUI.js")"></script>
<link href="@Url.Content("~/Content/TablesCss/demo_page.css")" rel="stylesheet">
<link href="@Url.Content("~/Content/TablesCss/header.ccss.css")" rel="stylesheet">
<link href="@Url.Content("~/Content/TablesCss/demo_table.css")" rel="stylesheet">
<script src="@Url.Content("~/Scripts/jquery.dataTables.js")" type="text/javascript"></script>
<script>
    $(function () {
        $("#tabs").tabs();
    });
    $(document).ready(function () {
        $("#RejectOrders").click(function () {
            
            var url = $URL._GetRejectedOrders + "/" + 1;
            var targetDiv = "#tabs-" + 2;
            var type = "UpdateOrders"
            showLoader();
            $.get(url, null, function (result) {
                $(targetDiv).html(result);
                hideLoader();
            });
        });

        $("#UpdateOrders").click(function () {
            
            var url=$URL._GetRejectedOrders+"/"+2;
            var targetDiv = "#tabs-" + 3;
            showLoader();
            $.get(url, null, function (result) {
                $(targetDiv).html(result);
                hideLoader();
            });
        });


    });
</script>
<section id="container">
    <section class="payment">
        <section>
            <div id="tabs" style="min-height: 600px">
                <ul>
                    <li><a href="#tabs-1" >New Inspection Orders</a></li>
                    <li><a href="#tabs-2" id="RejectOrders">Rejected Inspection Orders</a></li>
                    <li><a href="#tabs-3" id="UpdateOrders">Updated Inspection Orders</a></li>
                </ul>
                <div id="tabs-1">
                    <table style="width: 100%; float: right" cellpadding="0" cellspacing="0" border="0" class="table" id="tblMaintenanceReq">
                        <thead>
                            <tr>
                                <th width="70%" class="tbl_head bod_rgt">Property Address</th>
                                <th width="30%" class="tbl_head bod_rgt">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td class="bod_rgt">@item.OwnerFirstName @item.OwnerLastName, @item.StreetAddress,@item.City,@item.State,@item.Zip </td>
                                    <td class="bod_rgt"><a href="javascript://void(0);" data-orderid="@item.OrderID" id="anchorMaintenanceReq1">View Detail</a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div id="tabs-2">
                  @* @{Html.RenderPartial("_RejectedNotifications", Model);}*@
                </div>
                 <div id="tabs-3">
                @*   @{Html.RenderPartial("_UpdatedNotifications", Model);}*@
                </div>
            </div>
        </section>
    </section>
    <section class="clr"></section>
</section>
<!-- Loader-->
<div id="loadingModel" class="displayNone overlayPage">
    <div class=" loaderPage">
        <div>
            <img src='@Url.Content("~/Content/Images/loading_big.gif")' />
        </div>
        <div>
            Loading..
        </div>
    </div>
</div>
<!-- /Loader -->
<script type="text/javascript">
    $("#tblMaintenanceReq").dataTable();
   
    $(document).ready(function () {

        var DataJson = ""; 
        $("#RejectOrders").click(function () {
            
            $.getJSON($URL._GetRejectedOrders, {},
              function (classesData) {
                  classesData = $.parseJSON(classesData);
                  //var classesData1=classesData.length;
                  //alert(classesData1);
                  $.each(classesData, function (i, item) {

                      DataJson += "['" + item.OwnerFirstName + "','Internet Explorer 4.0'],"
                      
                      //DataJson += "['" + item.OwnerFirstName + "','test'],"

                  });

              });
            DataJson = DataJson.substr(0, DataJson.length - 1)
            $('#tblReject').dataTable({
                "aaData": [DataJson
                ],
                "aoColumns": [
                    { "sTitle": "Property Address" },
                    { "sTitle": "Action" }
                   
                ]
            });
        });
    });
        function showLoader() {
            $("#loadingModel").show();
        }
        function hideLoader() {
            $("#loadingModel").hide();
        }
    
</script>

SpectorMax/Views/UserInfoes/SellerDashboard.cshtml
@{
    ViewBag.Title = "SellerDashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using SpectorMax.Entities.Classes

<script type="text/javascript">
    $(document).ready(function () {
        $("#btnInviteFriend").click(function () {
            $(location).attr("href", $URL._InviteFriend + "?userId=@Sessions.LoggedInUser.UserId");
        });
        $("#btnPreClosingCheckList").click(function () {
            $(location).attr("href", $URL._PreClosingCheckListIndex + "?userId=@Sessions.LoggedInUser.UserId");
        });
        $("#btnCreateInspectionOrder").click(function () {
            $(location).attr("href", $URL._InsectionOrderDetailsCreate + "?userId=@Sessions.LoggedInUser.UserId");
        });
        $("#btnViewPreviousInspection").click(function () {
            $(location).attr("href", $URL._InsectionOrderDetails + "?userId=@Sessions.LoggedInUser.UserId");
        });
        $("#btnViewPreviousInvoices").click(function () {
            $(location).attr("href", $URL._PaymentsDetails + "?userId=@Sessions.LoggedInUser.UserId");
        });
        $("#btnPurchaseSubscriptionPlan").click(function () {
            $(location).attr("href", $URL._PaymentsIndex + "?userId=@Sessions.LoggedInUser.UserId");
        });
        $("#btnReferInspectorToFriend").click(function () {
            $(location).attr("href", $URL._ReferaFriend + "?userId=@Sessions.LoggedInUser.UserId");
        });
        $("#btnNotification").click(function () {
            $(location).attr("href", $URL._NotificationDashboard);
        });
        $("#UpdateStatus").click(function () {
            $(location).attr("href", $URL._NotificationDashboard + "?UpdateStatus=true");
        });

        if ("@Sessions.LoggedInUser.rolecount" == "2") {
            $("#liUserRole").css('display', 'block');
            //$("#btnUpgradeAccount").css('display', 'none');
            $("#ddlRole").change(function () {
                $(location).attr("href", $URL._BuyerDashBoard);
            });
        }
        $("#txtSearchLocation").keydown(function (event) {
            // Allow: backspace, delete, tab, escape, enter and .
            if ($.inArray(event.keyCode, [46, 8, 9, 27, 13, 190]) !== -1 ||
                // Allow: Ctrl+A
                (event.keyCode == 65 && event.ctrlKey === true) ||
                // Allow: home, end, left, right
                (event.keyCode >= 35 && event.keyCode <= 39)) {
                // let it happen, don't do anything
                return;
            }
            else {
                // Ensure that it is a number and stop the keypress
                if (event.shiftKey || (event.keyCode < 48 || event.keyCode > 57) && (event.keyCode < 96 || event.keyCode > 105)) {
                    event.preventDefault();
                }
            }
        });

        $("#btnSearchLocation").click(function () {
            if ($("#txtSearchLocation").val().length > 0) {
                $(location).attr("href", $URL._SearchInspector + "?ZipCode=" + $("#txtSearchLocation").val());
            }

        });
    });
</script>

<!--================container start===============-->
<section id="container">
    <section class="payment">
        @using (Html.BeginForm("Index", "InspectorRatings", FormMethod.Post, new { id = "zipcode" }))
        {
            <div id="SearchInspector" style="float: right; margin-bottom: 10px;">
                Find Inspector in your area
                <input type="text" id="txtSearchLocation" maxlength="6" name="txtSearchLocation" class="simple_input"/>
                <img style="display:none" id="ZipCodeProgressBar" alt="Progress Bar" src='@Url.Content("~/Images/loading_icon.gif")' />
                <input type="button" id="btnSearchLocation" class="btn" value="Go" />
            </div>  
            
            <div style="float: left; margin-bottom: 10px;">
                <ul>
                    <li id="liUserRole" style="display: none;">
                        <label style="margin-left: -8px;">Change Your Role:</label>
                        <select id="ddlRole" class="simple_input" style="width: 54% !important; float: right;">
                            <option value="1" selected="selected">Home Owners</option>
                            <option value="2">Potential Buyers</option>
                        </select>
                    </li>
                </ul>
            </div>
        }
        <div></div>
        <table style="height: 400px; width: 100%;">
            <tr>
                <td style="padding-left: 100px;">
                    <input type="button" id="btnCreateInspectionOrder" class="dbtn" value="Create Inspection Order" />
                </td>
                <td></td>
                <td style="padding-left: 100px;">
                    <input type="button" id="btnInviteFriend" class="dbtn" value="Invite a Friend" /></td>
            </tr>
            <tr>
                <td style="padding-left: 100px;">
                    <input type="button" id="btnViewPreviousInspection" class="dbtn" value="View Previous Inspections" />
                </td>
                <td></td>
                <td style="padding-left: 100px;">
                    <input type="button" id="btnReferInspectorToFriend" class="dbtn" value="Refer Inspector To Friend" /></td>
            </tr>
            <tr>
                <td style="padding-left: 100px;">
                    <input type="button" id="btnViewPreviousInvoices" class="dbtn" value="View Previous Invoices" />
                </td>
                <td></td>
                <td style="padding-left: 100px;">
                    <input type="button" id="btnNotification" class="dbtn" value="Notification(@ViewBag.count)"  />
                    <input type="button" id="UpdateStatus" title="@ViewBag.UpdateCount updates are available" style="color:black;background-color:highlight;border:0px solid;border-radius:20px;height: 30px;width: 30px;"  class="" value="@ViewBag.UpdateCount" />
                </td>
            </tr>
            <tr>
                <td style="padding-left: 100px;">
                    <input type="button" id="btnPreClosingCheckList" class="dbtn" value="Pre-Closing CheckList" />
                </td>
                <td></td>
                @*<td style="padding-left: 100px;">
                    <input type="button" id="btnPurchaseSubscriptionPlan" class="dbtn" value="Purchase Subscription Plan" /></td>*@
            </tr>
        </table>
        <section class="clr"></section>
    </section>
    <section class="clr"></section>
</section>
<!--===============container ends================-->

SpectorMax/Views/UserInfoes/_RejectedNotifications.cshtml
@model List<SpectorMax.Entities.Classes.PropertyAddress>

@using SpectorMax.Entities.Classes
<script src="@Url.Content("~/Scripts/FineUploader.js")" type="text/javascript"></script>
<link href="@Url.Content("~/Content/FineUpload.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/jquery.blockUI.js")"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#tblRejectNotifications").dataTable();
    });
</script>
<section class="payment">
    <h2>Notifications</h2>
    <section class="tbl_content">
        <table style="width: 100%; float: right" cellpadding="0" cellspacing="0" border="0" class="table" id="tblRejectNotifications">
            <thead>
                <tr>
                    <th width="70%" class="tbl_head bod_rgt">Property Address</th>
                    <th width="30%" class="tbl_head bod_rgt">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="bod_rgt">@item.OwnerFirstName @item.OwnerLastName, @item.StreetAddress,@item.City,@item.State,@item.Zip </td>
                        <td class="bod_rgt"><a href="javascript://void(0);" data-orderid="@item.OrderID" id="anchorMaintenanceReq1">View Detail</a></td>
                    </tr>
                }
            </tbody>
        </table>

    </section>
    <section class="clr"></section>
</section>